# Generated by Django 4.1 on 2024-06-05 20:14

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('missile_launchers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MissileRef',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('model_type', models.CharField(max_length=50, verbose_name='model')),
                ('manufacturer', models.CharField(blank=True, max_length=50)),
                ('speed', models.IntegerField()),
                ('operational_range', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Missile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('active', models.BooleanField(default=True)),
                ('launched', models.BooleanField(default=False)),
                ('launch_code', models.CharField(blank=True, max_length=8, validators=[django.core.validators.RegexValidator('^\\d{6}?$')])),
                ('missile_launcher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='missile_launchers.missilelauncher')),
                ('missile_model', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='missiles.missileref')),
            ],
        ),
    ]
